theme: jekyll-theme-slate
title: Bringing about 30 hospitals' price transparency data together
description: My large-scale data analysis showed confounding differences in prices for care at CT hospitals
